### ISSUE TITLE
CoreCLR not behaving the same as Desktop with % in form parsing

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/HttpAbstractions#129]
@Praburaj @Tratcher @GrabYourPitchforks 

Below is a small reproducible Program.cs and .json
Exception thrown only on CoreCLR in WebListener and IIS

program.cs:

```C#
using System;
using Microsoft.AspNet.WebUtilities;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            FormHelpers.ParseForm("UnEncoded=)(U%)(*(@*()$*");
            Console.WriteLine("Hello World");
            Console.ReadLine();
        }
    }
}
```

project.json:

```C#
{
    "dependencies": {
        "Microsoft.AspNet.WebUtilities": "1.0.0-*"
    },

    "frameworks" : {
        "aspnet50" : { },
        "aspnetcore50" : { 
            "dependencies": {
                "System.Console": "4.0.0.0"
            }
        }
    }
}
```

Exception Details:
System.UriFormatException was unhandled by user code
  HResult=-2146233033
  Message=Invalid URI: There is an invalid sequence in the string.
  Source=System
  StackTrace:
       at System.UriHelper.UnescapeString(Char* pStr, Int32 start, Int32 end, Char[] dest, Int32& destPosition, Char rsvd1, Char rsvd2, Char rsvd3, UnescapeMode unescapeMode, UriParser syntax, Boolean isQuery, Boolean readOnlyConfig)
       at System.UriHelper.UnescapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPosition, Char rsvd1, Char rsvd2, Char rsvd3, UnescapeMode unescapeMode, UriParser syntax, Boolean isQuery, Boolean readOnlyConfig)
       at System.Uri.UnescapeDataString(String stringToUnescape)
       at Microsoft.AspNet.WebUtilities.ParsingHelpers.ParseDelimited(String text, Char[] delimiters, Action`3 callback, Object state)
       at Microsoft.AspNet.WebUtilities.ParsingHelpers.GetForm(String text)
       at Microsoft.AspNet.WebUtilities.FormHelpers.ParseForm(String text)
       at ConsoleApp1.Program.Main(String[] args) in c:\users\brecon\documents\visual studio 14\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 10
  InnerException:

**Comment by Tratcher** [comment]
Should be handled by https://github.com/aspnet/HttpAbstractions/issues/72

**Comment by GrabYourPitchforks** [comment]
The new encoders won't address this since it's a decoding issue instead of an encoding issue. However, a proper fix for System.Uri is slowly winding its way through the branches, and we should see it bubble up to our layer soon.

**Comment by SidharthNabar** [comment]
@GrabYourPitchforks  @Tratcher 

This should be fixed in the CTP6 version of System.Uri - please try it and let us know if you can still reproduce the issue.

Thanks,
Sidharth
[.NET Networking team]

**Comment by BrennanConroy** [comment]
Looks fixed.
