### ISSUE TITLE
Unit test Microsoft.AspNet.Html.Abstractions.Test.HtmlContentBuilderExtensionsTest.Builder_AppendFormat_WithDifferentCurrentCulture fails on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/HttpAbstractions#442]
Assert.Equal() Failure
                                ↓ (pos 12)
          Expected: HtmlEncode[[01 February 2015]]
          Actual:   HtmlEncode[[Sunday, 1 February 2015]]
                                ↑ (pos 12)
          Stack Trace:
               at Microsoft.AspNet.Html.Abstractions.Test.HtmlContentBuilderExtensionsTest.Builder_AppendFormat_WithDifferentCurrentCulture()
               at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
               at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
               at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by cesarbs** [comment]
Opened CoreCLR issue https://github.com/dotnet/corefx/issues/3974
