### ISSUE TITLE
Exception thrown if no body is included when an IFormFile is expected

### ISSUE THREAD

**Issue by vaindil** [aspnet/HttpAbstractions#747]
_(Sorry, not sure if this belongs in this repo or another one. I also opened aspnet/Mvc#5631.)_

Typical behavior when a parameter is not included in a request is to make that parameter null. With the below code, however, I'm getting an exception if the request body is blank. The exception happens before the controller is called. If the body isn't blank but an invalid parameter is specified, the code performs as expected--the controller is reached but the relevant parameter is null.

> IOException: Unexpected end of Stream, the content may have already been read by another component.

Function:

```csharp
[HttpPost]
public async Task<IActionResult> Upload(IFormFile image)
{
    // body isn't necessary
}
```

Request body is empty, exception is thrown whether `Content-Type` is specified or not.

```
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer <token here>
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Content-Type: multipart/form-data
```

Stack trace:

```
System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component. 
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.<ReadAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.<DrainAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.<ReadNextSectionAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.<AddValueProviderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.<CreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindArgumentsCoreAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by khellang** [comment]
I think might belong in the MVC repo, since it's MVC that tries to read the empty stream.

**Comment by vaindil** [comment]
@khellang Got it, I'll submit this over there. Thanks!

**Comment by khellang** [comment]
It _could_ also be the form reader (in this repo) that's the culprit. I'm not sure where, if anywhere, the bug is :stuck:

**Comment by vaindil** [comment]
Heh, alright. I'll reopen it until I hear otherwise then. :P

**Comment by vaindil** [comment]
@khellang Just saw your edited comment. A POST without a body is valid, at least according to [this message](https://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0276.html) on the HTTP-WG list (found from [this SO question](https://stackoverflow.com/questions/7323958/are-put-and-post-requests-required-expected-to-have-a-request-body)). Since the actual request is technically valid, it should be left to me to determine when to throw a 400. IMO an empty body should be treated the same regardless of the expected content.

**Comment by Tratcher** [comment]
The HTTP request is valid, but the body format isn't. How the server/framework should try to handle this error is a question for MVC.

**Comment by vaindil** [comment]
@Tratcher Good point. Turns out this is a problem when `Content-Type` is `multipart`, in which case [a body is required](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).

> The body must then contain one or more "body parts," each preceded by an encapsulation boundary, and the last one followed by a closing boundary.

I was unaware of this from the spec. I still think it should return a 400 and not a 500, but as you said that's for the MVC team to decide.

I'll close this issue then. Thank you!

**Comment by khellang** [comment]
That's what I was referring to when I said "valid" request :smile:
