### ISSUE TITLE
Intermittent NullReferenceException in DefaultHttpContext.get_Items()

### ISSUE THREAD

**Issue by neoGeneva** [aspnet/HttpAbstractions#839]
I'm getting an intermittent NullReferenceException in my ASPNET Core MVC 1.1.3

So far I've seen the issue twice (in a action that's executed a dozen times a day) in the last two days in my production environment, I've spent the last day trying to replicate it in development, but I haven't been able to, and after digging through the code in Microsoft.AspNetCore.Http.Features and Microsoft.AspNetCore.Mvc.Core I'm struggling to see what value could be null that'd generate this error.

The full stack trace I get is:

```
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelperFactory.GetUrlHelper(ActionContext context)
   at Microsoft.AspNetCore.Mvc.ControllerBase.get_Url()
   at RubberMonkey.Sales.Web.Controllers.CheckoutController.<ConfirmInternal>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at RubberMonkey.Sales.Web.Controllers.CheckoutController.<AdminConfirm>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
```

I'm not comfortable making my codebase public, though I'd like to do whatever else I can to help understand what can cause this.

**Comment by neoGeneva** [comment]
Some more details about my hosting environment:

- Hosted on an Azure VM: Windows 2012 R2
- IIS 8
- dotnet --version
    Microsoft .NET Core Shared Framework Host
    Version  : 1.1.0
    Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
- Microsoft.AspNetCore.Http.dll version 1.1.2
- Microsoft.AspNetCore.Mvc.Core.dll version 1.1.3

**Comment by rynowak** [comment]
You're not trying to do anything that touches the `HttpContext` on a background thread are you? None of these types are thread safe, and that's what this sounds like...

**Comment by neoGeneva** [comment]
@rynowak yeah, I had considered the same thing, that maybe I had an async method that wasn't being awaited, or something along those lines, but I haven't found it yet, I'll have another look and see if I have a background thread that might be accessing the `HttpContext`.

**Comment by neoGeneva** [comment]
I think @rynowak is right, this was a threading issue. 

I have a background thread doing something along the lines of `IHttpContextAccessor.HttpContext.RequestServices` and I'm 90% sure that's what's causing me the problems, so I'm going to close this issue for now.

Thanks

**Comment by rgmills** [comment]
Hi, I'm seeing a similar intermittent `NullReferenceException`.  We don't have a code path under our domain that accesses any instance of `HttpContext.Items` from a background thread.  The only access is from an implementation of `IActionFilter`.

Similar environment to what @neoGeneva mentioned above

```
2017-05-23 09:49:13.349 -04:00 [Error] [Microsoft.AspNetCore.Server.Kestrel] [0HL51D1D44CVS] Connection id ""0HL51D1D31K2M"": An unhandled exception was thrown by the application.
System.ObjectDisposedException: The response has been aborted due to an unhandled application exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.<>c.<OnResourceExecuting>b__3_0(Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<FireOnStarting>d__177.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAbortedException()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<InitializeResponseAwaited>d__192.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<WriteAsyncAwaited>d__183.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.<FlushInternalAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyService.Infrastructure.Tokens.TokenContextMiddleware.<Invoke>d__7.MoveNext() in C:\build\src\MyService\Infrastructure\Tokens\TokenContextMiddleware.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyService.Middleware.MyServiceCsrfMiddleware.<Invoke>d__7.MoveNext() in C:\build\src\MyService\Middleware\MyServiceCsrfMiddleware.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by davidfowl** [comment]
Does your application ever touch the http context on a background thread?

**Comment by rynowak** [comment]
I'm wondering about this: 
```
 at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.<>c.<OnResourceExecuting>b__3_0(Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<FireOnStarting>d__177.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAbortedException()
```

**Comment by rgmills** [comment]
> Does your application ever touch the http context on a background thread?

Best I can tell, no.  We will touch HttpContext within Controllers, Middleware and Filters none of which would move those accesses to a background thread.  We pull the interesting values we need internally into our own context object and propagate through our stack.

**Comment by Tratcher** [comment]
@davidfowl doesn't this look a lot like the issue with AppInsights touching the context on HttpClient's background thread?

**Comment by rgmills** [comment]
`Microsoft.ApplicationInsights.AspNetCore` 2.0.0 is referenced, but we don't currently have it configured.  I should probably get that removed anyway, but can get a release out to prod tonight and provide feedback if that'd be useful.

**Comment by rgmills** [comment]
Released an update in our production environment with AppInsights removed and exception still occurred.

A bit more information:
- We have HAProxy that invoke a health check endpoint, this is the only endpoint we've seen the exception surface.
- This endpoint in the last 24 hours was invoked nearly 500,000 and only once did the exception occur.  The frequency went down from 10-15 occurrences over a different 24 hour period (same request load).

Here's high level what happens within the controller method:

```
[HttpGet]
[AllowAnonymous]
public async Task<IActionResult> Get()
{
	var result = await StatusService.HeartbeatAsync();

	var objectResult = new ObjectResult(result)
	{
		StatusCode = result.Failed ? 503 : 200
	};

	if (result.Failed)
	{
		int substatusCode = 0;
		if (result.IsKillswitched)
		{
			substatusCode = 501;
		}
		else if (result.Redis.Failed)
		{
			substatusCode = 502;
		}
		else if (result.ShareFile.Failed)
		{
			substatusCode = 503;
		}

		HttpContext.Response.Headers.Add("SubStatusCode", substatusCode.ToString());
	}

	return objectResult;
}
```

Within `HeartbeatAsync` we query a few internal services (Redis, DB, external API) to make sure they are up and make sure we aren't explicitly attempting to drop this server out (based on a file on disk)

**Comment by davidfowl** [comment]
@rgmills you're sure it's this end point causing issues?

**Comment by rgmills** [comment]
@davidfowl Sorry, been on vacation.  About 100% confident it's this endpoint based on `HttpContext.TraceIdentifier` plus general timing of it occurring tends to be outside of any other request traffic.

**Comment by muratg** [comment]
Closing per triage team's decision.  We should document the fact that HttpContext is not thread safe better.  Filed a doc bug here: https://github.com/aspnet/Docs/issues/3916 

cc @Rick-Anders

**Comment by kevin-meyer-aarons** [comment]
> doesn't this look a lot like the issue with AppInsights touching the context on HttpClient's background thread?

@Tratcher Do you know if there's still an HttpContext issue with App Insights?  Is it knew to net core 2.0?

I have a custom `HttpClientHandler ` that accesses `HttpContext ` to pass along a correlation ID.  It's started to occasionally fail when I upgraded a project from aspnet core 1.1 to 2.0.3.  I don't see where I'm using it after `ConfigureAwait`, so I'm guessing the handler may be running on another thread internally.

**Comment by Tratcher** [comment]
As far as I know AI dealt with their issue by pre-populating their data structures. I wouldn't expect this issue in a HttpClientHandler wrapper, HttpClient is largely synchronous setting up the request until it gets into the HttpClientHandler and then jumps threads. Do you have a stack trace similar to above?

**Comment by kevin-meyer-aarons** [comment]
@Tratcher thank you for the reply.  It turns out I had multiple concurrent tasks using instances of my `HttpClientHandler` which read and modified `HttpContext.Items`.  I looked at the App Insights aspnetcore client code and it looks like they simply `lock` the reference to `HttpContext` that comes from the accessor (https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/80c24f1d7d148ef69d25eec58d759a6719d6a487/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs).  I implemented the same and it seems to have solved my problem.  e.g., 
```
var httpContext = accessor.HttpContext;
lock(httpContext) {
  // interact with httpContext.Items
}
```

**Comment by davenewza** [comment]
I am experiencing the same problem, I believe it may come from the following middleware implementation:

```csharp
public async Task Invoke(HttpContext context)
{
    // Callback to add the RequestId to the response.
    context.Response.OnStarting(state =>
    {
        var httpContext = (HttpContext)state;
        httpContext.Response.Headers.Add("requestId", RequestId.);
        return Task.CompletedTask;
    }, context);

    await next(context);
}
```

Is it possible that the `OnStarting` callback, which is mutating `HttpContext`, could cause this?

**Comment by davenewza** [comment]
I see now that this repo's issue tracker is closed.  I have thus posted my issue here https://github.com/aspnet/Home/issues/2799
