### ISSUE TITLE
Intermittent NullReferenceException at DefaultHttpRequest.get_Cookies()

### ISSUE THREAD

**Issue by PuttItOut** [aspnet/HttpAbstractions#911]
This exception is random but occurs fairly frequently.

## Configuration
- Core 2 Preview 2 Final
- Windows 2012 R2 / IIS
- ASPNETCORE_ENVIRONMENT=Development

## Stack
~~~
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Cookies()

   at Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.GetRequestCookie(HttpContext context, String key)

   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<ReadCookieTicket>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleAuthenticateAsync>d__20.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<AuthenticateAsync>d__47.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationService.<AuthenticateAsync>d__10.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
~~~

**Comment by Tratcher** [comment]
get_Cookies() lazily initializes and parses the request cookies. This error commonly happens when multiple threads are attempting to access the same HttpContext object.

That said, I don't see any user code on this stack. Can you share the Startup for this app?

**Comment by PuttItOut** [comment]
All source code is located here: https://github.com/voat/voat/tree/Core

**Comment by PuttItOut** [comment]
I see a lot of these log entries:
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
Microsoft.AspNetCore.Hosting.Internal.WebHost

Could diagnostics be triggering this?

**Comment by davidfowl** [comment]
@PuttItOut I was trying to find places in your code where you use `IHttpContextAccessor`, that's the most common cause of potential issues like this. Somebody is accessing the "current" `HttpContext` from various threads implicitly.

**Comment by Tratcher** [comment]
Only if they were happening from a different thread. Application Insights has been known to cause similar issues when doing diagnostics from a background thread inside HttpClient.

**Comment by PuttItOut** [comment]
@davidfowl I will begin to look for this. This code base is a port from 4.6, with a few work-around areas, so there may be code that needs further refactoring.

I'm looking for any Task or separate thread that is acquiring a questionable ref to `HttpContext` correct?

Any chance this issue can be trapped for future ease of fixing? Just wondering.

**Comment by davidfowl** [comment]
Places to start:
- Any use of `IHttpContextAccessor`
- Any call to Task.Run

**Comment by voat** [comment]
Just a quick update:
I think I have found the culprit. Code has a queued logger that, I believe, is holding references indirectly to Http objects. When it attempts to serialize (on a separate thread) it is navigating these references.

Once I trap and test this and it works I will close this issue.

**Comment by PuttItOut** [comment]
It does indeed appear I was holding references to Http components with the logging code I was using. I have serialized before queueing log entries and this particular bug has not presented itself after this change.

Thank you for the help with this.
